#!/bin/bash
options=(
  width=5
  "inactive_color=gradient(top_left=0x4D37f499,bottom_right=0x4D04d1f9)" \
  "active_color=gradient(top_left=0xff37f499,bottom_right=0xff04d1f9)" \
)

borders "${options[@]}"

