include dracula.conf

# Font
font_size 18
font_family JetBrains Mono
# Nerd Fonts v2.3.3
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6AA,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F0001-U+F1AF0 Symbols Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto
disable_ligatures never

#: Kitty modifier key
kitty_mod ctrl+shift

# Cursor
cursor #FF5555
cursor_text_color #f8f8f2
cursor_shape block
cursor_blink_interval 1

# Scrollback
scrollback_lines 10000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
scrollback_pager_history_size 4096

# Mouse
url_color #8BE9FD
url_style dotted
open_url_with default
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
detect_urls yes
underline_hyperlinks always
copy_on_select clipboard
paste_actions quote-urls-at-prompt
mouse_map right click grabbed,ungrabbed paste_from_clipboard

# Performance Tuning
repaint_delay 1
input_delay 1
sync_to_monitor yes

# Terminal bell
enable_audio_bell no
visual_bell_duration 0
bell_on_tab "🔔"

# Window layout
remember_window_size yes
draw_minimal_borders yes
window_margin_width 0
single_window_margin_width -1
window_padding_width 0
single_window_padding_width -1
active_border_color #BD93F9
window_border_width 0.5
background_opacity 0.9
hide_window_decorations titlebar-only
confirm_os_window_close 0
background_blur 20
background_tint 0.9
selection_foreground #f8f8f2
selection_background #BD93F9


# Tab bar
tab_bar_edge top
tab_bar_style powerline
tab_bar_alignment left
tab_bar_min_tabs 2


# Advanced
editor .
allow_remote_control yes
update_check_interval 12
# startup_session launch.conf
clipboard_max_size 512
allow_hyperlinks yes
shell_integration enabled
term xterm-kitty
## OS Specific Tweaks
### MacOS
macos_show_window_title_in none
macos_option_as_alt yes
macos_window_resizable yes
macos_custom_beam_cursor yes
### Wayland
linux_display_server wayland

# Keyboard shortcuts
map cmd+enter no_op
## Copy/Paste
map kitty_mod+v paste_from_clipboard
map ctrl+shift+c copy_to_clipboard
map cmd+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map kitty_mod+c copy_to_clipboard
map cmd+v paste_from_clipboard
## Scrolling
map ctrl+shift+up scroll_page_up
map cmd+up scroll_page_up
map ctrl+shift+down scroll_page_down
map cmd+down scroll_page_down
### Shell integration
map kitty_mod+shift+j scroll_to_prompt 1
map kitty_mod+shift+k scroll_to_prompt -1
map kitty_mod+shift+o show_last_command_output
### Window/misc settings
map kitty_mod+n new_os_window
### Tab keybinds
map kitty_mod+1 goto_tab 1
map kitty_mod+2 goto_tab 2
map kitty_mod+3 goto_tab 3
map kitty_mod+4 goto_tab 4
map kitty_mod+5 goto_tab 5
map kitty_mod+right next_tab
map kitty_mod+left previous_tab
map kitty_mod+w close_tab
map kitty_mod+t new_tab
### Font Management
map kitty_mod+plus change_font_size all +1.0
map kitty_mod+minus change_font_size all -1.0
### Miscellaneous
map f11 toggle_fullscreen
map f12 kitten unicode_input
map kitty_mod+shift+plus set_background_opacity +0.1
map kitty_mod+shift+minus set_background_opacity -0.1
map kitty_mod+shift+k scrollback active
map kitty_mod+shift+r load_config_file
### Marks
map f1 toggle_marker text 1 TEST 
map f2 toggle_marker text 2 ERROR
