[global]
device_name = "ArchVoid"
bitrate = 320
dbus_type = "session"
backend = "pulseaudio"
volume_controller = "alsa"
autoplay = true
zeroconf_port = 7777
device_type = "computer"
username = "j9xinca"
cache_path = "/home/$USER/.cache/spotify"
password_cmd = "\\cat ~/.config/spotifyd/.env"
no_audio_cache = true
initial_volume = "40"
volume_normalisation = false
