"ui.background" = "#212337"
"ui.text" = "#ebfafa"
"ui.selection" = "#bf4f8e"

[palette]
default = "#ebfafa"
black = "#212337"
red = "#f16c75"
green = "#37f499"
yellow = "#f1fc79"
blue = "#04d1f9"
magenta = "#a48cf2"
cyan = "#39DDFD"
light-red = "#f0313e"
light-green = "#33C57F"
light-yellow = "#c0c95f"
light-magenta = "#bf4f8e"
light-cyan = "#10A1BD"
light-gray = "#ABB4DA"
white = "#ebfafa"
