attribute = { fg = "#04d1f9" }
comment = { fg = "#7081d0", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#ffc777" }
constant = { fg = "#f1fc79" }
"constant.builtin" = { fg = "#39DDFD" }
"constant.builtin.boolean" = { fg = "#f7c67f" }
"constant.character" = { fg = "#c3e88d" }
"constant.character.escape" = { fg = "#c099ff" }
"constant.numeric" = { fg = "#f7c67f" }
"constant.numeric.float" = { fg = "#f7c67f" }
"constant.numeric.integer" = { fg = "#f7c67f" }
constructor = { fg = "#65bcff" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { fg = "#7ca1f2" }
"diff.delta.moved" = { fg = "#82aaff" }
"diff.minus" = { fg = "#e26a75" }
"diff.plus" = { fg = "#b8db87" }
error = { fg = "#c53b53" }
function = { fg = "#82aaff" }
"function.builtin" = { fg = "#65bcff" }
"function.macro" = { fg = "#86e1fc" }
"function.method" = 
"function.special" = { fg = "#86e1fc" }
hint = { fg = "#4fd6be" }
info = { fg = "#0db9d7" }
keyword = { fg = "#fca7ea", modifiers = ["italic"] }
"keyword.control" = { fg = "#c099ff" }
"keyword.control.conditional" = { fg = "#c099ff" }
"keyword.control.exception" = { fg = "#c099ff" }
"keyword.control.repeat" = { fg = "#c099ff" }
"keyword.control.return" = { fg = "#fca7ea", modifiers = ["italic"] }
"keyword.directive" = { fg = "#86e1fc" }
"keyword.function" = { fg = "#c099ff" }
"keyword.operator" = { fg = "#c099ff" }
label = { fg = "#82aaff" }
"markup.bold" = { fg = "#c8d3f5", modifiers = ["bold"] }
"markup.heading" = 
"markup.heading.completion" = { bg = "#1e2030", fg = "#c8d3f5" }
"markup.heading.hover" = { bg = "#363c58" }
"markup.italic" = { fg = "#c8d3f5", modifiers = ["italic"] }
"markup.link" = { fg = "#82aaff", underline = { style = "line" } }
"markup.link.label" = { fg = "#4fd6be" }
"markup.link.text" = { fg = "#4fd6be" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#f7c67f", modifiers = ["bold"] }
"markup.normal.completion" = { fg = "#636da6" }
"markup.normal.hover" = { fg = "#828bb8" }
"markup.raw" = { fg = "#4fd6be" }
"markup.raw.block" = { fg = "#4fd6be" }
"markup.raw.inline" = { bg = "#444a73", fg = "#82aaff" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = 
operator = { fg = "#89ddff" }
special = { fg = "#65bcff" }
string = { fg = "#c3e88d" }
"string.regexp" = { fg = "#b4f9f8" }
"string.special" = { fg = "#65bcff" }
tag = { fg = "#c099ff" }
type = { fg = "#65bcff" }
"type.builtin" = { fg = "#589ed7" }
"type.enum" = { fg = "#65bcff" }
"type.enum.variant" = { fg = "#f7c67f" }
"ui.background" = { bg = "bg" }
"ui.cursor" = { bg = "#c8d3f5", fg = "#222436" }
"ui.cursor.match" = { fg = "#f7c67f", modifiers = ["bold"] }
"ui.linenr" = { fg = "#3b4261" }
"ui.linenr.select" = { fg = "#737aa2" }
"ui.menu" = { bg = "#1e2030", fg = "#c8d3f5" }
"ui.menu.scroll" = { bg = 2698042, fg = 3883617 }
"ui.menu.selected" = { bg = "#363c58" }
"ui.popup" = { bg = "#1e2030", fg = "#589ed7" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#1e2030", fg = "#828bb8" }
"ui.statusline.inactive" = { bg = "#1e2030", fg = "#3b4261" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { bg = "#222436", fg = "#c8d3f5" }
"ui.text.focus" = { bg = "#2d3f76" }
"ui.text.inactive" = { fg = "#636da6", modifiers = ["italic"] }
"ui.text.info" = { bg = "#1e2030", fg = "#c8d3f5" }
"ui.virtual.inlay-hint" = { bg = "#273644", fg = "#4fd6be" }
"ui.window" = { fg = "#1b1d2b", modifiers = ["bold"] }
variable = { fg = "#c8d3f5" }
"variable.builtin" = { fg = "#ff757f" }
"variable.other.member" = { fg = "#4fd6be" }
"variable.parameter" = { fg = "#ffc777" }
warning = { fg = "#ffc777" }

[palette]
bg_dark = "#171928",
bg = "#212337",
bg_highlight = "#292e42",
terminal_black = "#414868",
fg = "#ebfafa",
fg_dark = "#ABB4DA",
fg_gutter = "#3b4261",
dark3 = "#6473B7",
comment = "#7081d0",
dark5 = "#5866A2",
cyan = "#04d1f9",
bright_cyan = "#39DDFD",
dark_cyan = "#10A1BD",
magenta = "#a48cf2",
magenta2 = "#bf4f8e",
magenta3 = "#722f55",
pink = "#f265b5",
purple = "#a48cf2",
orange = "#f7c67f",
yellow = "#f1fc79",
dark_yellow = "#c0c95f",
green = "#37f499",
dark_green = "#33C57F",
red = "#f16c75",
bright_red = "#f0313e",
"delta.add" = "#305f6f"
"delta.delete" = "#6b2e43"
"diff.add" = "#273849"
"diff.change" = "#252a3f"
"diff.delete" = "#3a273a"
"diff.text" = "#394b70"
error = "#c53b53"
"git.add" = "#37f499"
"git.change" = "#7081d0"
"git.delete" = "#f16c75"
"git.ignore" = "#545c7e"
"gitSigns.add" = "#627259"
"gitSigns.change" = "#485a86"
"gitSigns.delete" = "#b55a67"
