inherits = "tokyonight_moon"
"ui.background" = { fg = "foreground" }

[palette]
bg_dark = "#171928"
bg = "#212337",
bg_highlight = "#292e42",
terminal_black = "#414868",
fg = "#ebfafa",
fg_dark = "#ABB4DA",
fg_gutter = "#3b4261",
dark3 = "#6473B7",
comment = "#7081d0",
dark5 = "#5866A2",
cyan = "#04d1f9",
bright_cyan = "#39DDFD",
dark_cyan = "#10A1BD",
magenta = "#a48cf2",
magenta2 = "#bf4f8e",
magenta3 = "#722f55",
pink = "#f265b5",
purple = "#a48cf2",
orange = "#f7c67f",
yellow = "#f1fc79",
dark_yellow = "#c0c95f",
green = "#37f499",
dark_green = "#33C57F",
red = "#f16c75",
bright_red = "#f0313e",
"delta.add" = "#305f6f"
"delta.delete" = "#6b2e43"
"diff.add" = "#273849"
"diff.change" = "#252a3f"
"diff.delete" = "#3a273a"
"diff.text" = "#394b70"
error = "#c53b53"
"git.add" = "#37f499"
"git.change" = "#7081d0"
"git.delete" = "#f16c75"
"git.ignore" = "#545c7e"
"gitSigns.add" = "#627259"
"gitSigns.change" = "#485a86"
"gitSigns.delete" = "#b55a67"
