[mgr]
ratio = [1,4,3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
linemode = "permissions"
show_hidden = true
show_symlink = true
mouse_events = ["scroll"]

[preview]
wrap = "yes"
tab_size = 2

[preview.syntax]
theme = "Eldritch"
background = "#212337"

[opener]
play = [
  {run = 'celluloid "$@"', orphan = true, for="unix"}
]
edit = [
  { run = '$EDITOR "$@"', block=true, for="unix"}
]
open = [
  { run = 'xdg-open "$@"', desc="Open"}
]

[tasks]
image_bound = [ 20000, 20000]

[input]
cursor_blink = true


